const chatActionTypes = {
    'SET_CHATS': 'SET_CHATS',
    'ADD_NEW_CHAT': 'ADD_NEW_CHAT',
    'UPDATE_CHAT': 'UPDATE_CHAT',
    'ACCESS_CHAT': 'ACCESS_CHAT',
    'FETCH_CHATS': 'FETCH_CHATS',
    'CREATE_GROUP_CHAT': 'CREATE_GROUP_CHAT',
    'RENAME_GROUP': 'RENAME_GROUP',
    'ADD_USER': 'ADD_USER',
    'REMOVE_USER': 'REMOVE_USER',
    'CREATED_GROUP_SUCCESSFULLY': 'CREATED_GROUP_SUCCESSFULLY',
    'NEW_CHAT': 'NEW_CHAT'
}

export default chatActionTypes;