const groupOperationsActionTypes = {
    'SET_SEARCH_RESULT': 'SET_SEARCH_RESULT',
    'SEARCH_USER_WITH_NAME': 'SEARCH_USER_WITH_NAME',
    'SET_SELECTED_USERS': 'SET_SELECTED_USERS',
    'ADD_TO_SELECTED_USERS': 'ADD_TO_SELECTED_USERS',
    'ADD_SELECTED_USER': 'ADD_SELECTED_USER',
    'REMOVE_SELECTED_USER': 'REMOVE_SELECTED_USER',
    'SET_EXISTING_IDS': 'SET_EXISTING_IDS',
    'ADD_TO_EXISTING_ID': 'ADD_TO_EXISTING_ID',
    'CLEAR_GROUP_OPERATIONS_DATA': 'CLEAR_GROUP_OPERATIONS_DATA'
}

export default groupOperationsActionTypes;